# Generated by Django 4.2.7 on 2023-11-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
